### ISSUE TITLE
Thumbnail and image not appearing

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/maps#71]
event "Tradition of Amsterdam", can't see any problem with image file

**Comment by yuvadm** [comment]
This happened because the old file had hebrew chars, and when the new file was updated it didn't get thumbnails generated. I did that manually and it looks good now.

Note that for performance reasons I'm not updating thumbnails on media files, so if a bad file is uploaded, it either needs to be fixed manually by me, or simply deleted, and create a new media object instead.
